# Generated by Django 5.1.6 on 2025-02-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('district', models.CharField(default='Perambalur', max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('ward', models.CharField(choices=[('1st ward', '1st ward'), ('2nd ward', '2nd ward'), ('3rd ward', '3rd ward'), ('4th ward', '4th ward'), ('5th ward', '5th ward'), ('6th ward', '6th ward'), ('7th ward', '7th ward'), ('8th ward', '8th ward'), ('9th ward', '9th ward'), ('10th ward', '10th ward'), ('11th ward', '11th ward'), ('12th ward', '12th ward')], max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_num', models.CharField(max_length=12, unique=True, verbose_name='ID Number')),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='id_photos/')),
            ],
        ),
    ]
