# Generated by Django 5.1.6 on 2025-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='id_photo',
            field=models.ImageField(default='null', upload_to='id_photos/'),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='photo',
            field=models.ImageField(default='null', upload_to='profile_photos/'),
        ),
    ]
