# Generated by Django 5.1.6 on 2025-02-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_register_model_id_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.ImageField(upload_to='slider_photos/')),
                ('slider2', models.ImageField(upload_to='slider_photos/')),
                ('slider3', models.ImageField(upload_to='slider_photos/')),
            ],
        ),
    ]
