# Generated by Django 5.1.6 on 2025-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_slider_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='feature_photos/')),
                ('img2', models.ImageField(upload_to='feature_photos/')),
                ('img3', models.ImageField(upload_to='feature_photos/')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=700)),
            ],
        ),
    ]
