# Generated by Django 5.1.6 on 2025-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_feature_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_model',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show , 1-hidden'),
        ),
        migrations.AddField(
            model_name='slider_model',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-show , 1-hidden'),
        ),
    ]
