# Generated by Django 5.1.6 on 2025-02-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_feedback_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_model',
            old_name='description',
            new_name='problem',
        ),
    ]
