# Generated by Django 5.1.6 on 2025-02-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_description_feedback_model_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
